using DadosFutebol.Interfaces;
using System.Reflection;

namespace DadosFutebol.Service
{
    public class FCServices : IFCServices
    {
        public Dictionary<string, string> ChavesProcuraHTML()
        {
            Dictionary<string, string> Dicionario = new Dictionary<string, string>
            {
                { "nome", "Table_profileCellAnchor__VU0JH" },
                { "nacionalidade", "Picture_image__H5fmC" },
                { "Posicao", "Table_tag__3Mxk9 generated_utility3sm__0pg6W generated_utility1lg__ECKe_" },
                { "Overall","Table_statCellValue____Twu"},
                { "Pace","Table_statCellValue____Twu"},
                { "Shooting","Table_statCellValue____Twu"},
                { "Passing","Table_statCellValue____Twu"},
                { "Dribbling","Table_statCellValue____Twu"},
                { "Defending","Table_statCellValue____Twu"},
                { "Physicality","Table_statCellValue____Twu" },
                { "PePreferido","Attribute_attributeValue__lb_M5" },
                { "Idade","Attribute_attributeValue__lb_M5" },

            };
            return Dicionario;
        }


        public Dictionary<string, string> TagsHTML()
        {
            Dictionary<string, string> Dicionario = new Dictionary<string, string>
            {
                { "Comentario", "<!--...-->"},
                { "DOCTYPE" , "<!DOCTYPE>"},
                { "a" , "<a>"},
                { "abbr" , "<abbr>"},
                { "acronym" , "<acronym>"},
                { "address" , "<address>"},
                { "applet" , "<applet>"},
                { "area" , "<area>"},
                { "article" , "<article>"},
                { "aside" , "<aside>"},
                { "audio" , "<audio>"},
                { "b" , "<b>"},
                { "base" , "<base>"},
                { "basefont" , "<basefont>"},
                { "bdi" , "<bdi>"},
                { "bdo" , "<bdo>"},
                { "big" , "<big>"},
                { "blockquote" , "<blockquote>"},
                { "body" , "<body>"},
                { "br" , "<br>"},
                { "button" , "<button>"},
                { "canvas" , "<canvas>"},
                { "caption" , "<caption>"},
                { "center" , "<center>"},
                { "cite" , "<cite>"},
                { "code" , "<code>"},
                { "col" , "<col>"},
                { "colgroup" , "<colgroup>"},
                { "data" , "<data>"},
                { "datalist" , "<datalist>"},
                { "dd" , "<dd>"},
                { "del" , "<del>"},
                { "details" , "<details>"},
                { "dfn" , "<dfn>"},
                { "dialog" , "<dialog>"},
                { "dir" , "<dir>"},
                { "div" , "<div>"},
                { "dl" , "<dl>"},
                { "dt" , "<dt>"},
                { "em" , "<em>"},
                { "embed" , "<embed>"},
                { "fieldset" , "<fieldset>"},
                { "figcaption" , "<figcaption>"},
                { "figure" , "<figure>"},
                { "font" , "<font>"},
                { "footer" , "<footer>"},
                { "form" , "<form>"},
                { "frame" , "<frame>"},
                { "frameset" , "<frameset>"},
                { "h1" , "<h1>"},
                { "head" , "<head>"},
                { "header" , "<header>"},
                { "hr" , "<hr>"},
                { "html" , "<html>"},
                { "i" , "<i>"},
                { "iframe" , "<iframe>"},
                { "img" , "<img>"},
                { "input" , "<input>"},
                { "ins" , "<ins>"},
                { "kbd" , "<kbd>"},
                { "label" , "<label>"},
                { "legend" , "<legend>"},
                { "li" , "<li>"},
                { "link" , "<link>"},
                { "main" , "<main>"},
                { "map" , "<map>"},
                { "mark" , "<mark>"},
                { "meta" , "<meta>"},
                { "meter" , "<meter>"},
                { "nav" , "<nav>"},
                { "noframes" , "<noframes>"},
                { "noscript" , "<noscript>"},
                { "object" , "<object>"},
                { "ol" , "<ol>"},
                { "optgroup" , "<optgroup>"},
                { "option" , "<option>"},
                { "output" , "<output>"},
                { "p" , "<p>"},
                { "param" , "<param>"},
                { "picture" , "<picture>"},
                { "pre" , "<pre>"},
                { "progress" , "<progress>"},
                { "q" , "<q>"},
                { "rp" , "<rp>"},
                { "rt" , "<rt>"},
                { "ruby" , "<ruby>"},
                { "s" , "<s>"},
                { "samp" , "<samp>"},
                { "script" , "<script>"},
                { "section" , "<section>"},
                { "select" , "<select>"},
                { "small" , "<small>"},
                { "source" , "<source>"},
                { "span" , "<span>"},
                { "strike" , "<strike>"},
                { "strong" , "<strong>"},
                { "style" , "<style>"},
                { "sub" , "<sub>"},
                { "summary" , "<summary>"},
                { "sup" , "<sup>"},
                { "svg" , "<svg>"},
                { "table" , "<table>"},
                { "tbody" , "<tbody>"},
                { "td" , "<td>"},
                { "template" , "<template>"},
                { "textarea" , "<textarea>"},
                { "tfoot" , "<tfoot>"},
                { "th" , "<th>"},
                { "thead" , "<thead>"},
                { "time" , "<time>"},
                { "title" , "<title>"},
                { "tr" , "<tr>"},
                { "track" , "<track>"},
                { "tt" , "<tt>"},
                { "u" , "<u>"},
                { "ul" , "<ul>"},
                { "var" , "<var>"},
                { "video" , "<video>"},
                { "wbr" , "<wbr>"}
            };
            return Dicionario;
        }
    }
}
